### ISSUE TITLE
Chapter02 - Case Study - Notebook

### ISSUE THREAD

**Issue by ModarYaghi** [PacktPublishing/Python-3-Object-Oriented-Programming-Third-Edition#3]
Though I'm not new to Python 3, but I am in case of OOP. 
I just start reading the book, and I faced an issue with the case study of chapter02: Notebook. 
I wrote the code of the case as the book guided, but it didn't work as it should do.
The issue is that after adding some notes, the show function, search, and quit are working very well, but the modify function is the problem!.
The steps of the modify function show up as expected, but it works only on the first note, but not for the second and after.
It confused me very much, how it could be working for note id 1 and not for note id 2, 3, 4, ...etc?!
The steps are working always as I said, but nothing is modified when showing the notes after modifying them except note of id 1.
I reviewed the code many many times, also I compared them with the provided code files, they are the same as identical, even though the the source code worked perfectly after I downloaded them to my machine. It is extremely odd to me!.
Any suggestions?
Any way, I liked the book, I chose it over many others that have the same purpose.
I have one complain, I just hoped that it has more explanation for the code and how it works and related. 
But, very much thanks for the author and all contributors.

**Comment by dusty-phillips** [comment]
Try putting `print()` statements after each line in the methods to see what the values are. For example, you could put `print(note)` after the `note = self._find_note(id)` call to see if the note was found or not. If it wasn't found, you know the problem is in `_find_note`. So put `print(self.notes)` before the loop in `_find_notes` to make sure it is there.

My best guess is that you are trying to compare values of different types; for example, if `note.id` is an integer and `note_id` is a string, then they will not match because `1 == "1"` is `False`. That's why the two values are converted to strings at this line: https://github.com/PacktPublishing/Python-3-Object-Oriented-Programming-Third-Edition/blob/79ed9980847c57e32585830c1985e6bc5b9a500e/Chapter02/Case%20Study_%20Notebook/notebook.py#L46
